# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-06 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configures', '0003_auto_20180606_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nginxdb',
            name='projectname',
        ),
        migrations.RemoveField(
            model_name='phpfpmdb',
            name='projectname',
        ),
    ]
