# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180403_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbmanage',
            name='group',
            field=models.IntegerField(),
        ),
    ]
