# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-04 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180525_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbmanage',
            name='group',
            field=models.CharField(max_length=300),
        ),
    ]
