# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBA_Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('sql_action_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dev_Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('ops_to_online_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='left_nav',
            fields=[
                ('left_navid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('left_nav_pid', models.IntegerField()),
                ('left_nav_title', models.CharField(max_length=50)),
                ('left_nav_url', models.CharField(max_length=240)),
                ('left_nav_sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ops_Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('ops_to_pre_status', models.BooleanField()),
                ('ops_to_online_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('filelist', models.TextField()),
                ('release_status', models.CharField(max_length=50)),
                ('developer_name', models.CharField(max_length=30)),
                ('last_user_id', models.IntegerField(blank=True, null=True)),
                ('begin_time', models.DateTimeField(blank=True, null=True)),
                ('last_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
