# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0004_auto_20180403_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ope_Release',
            new_name='ops_release',
        ),
    ]
