# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0005_auto_20180403_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ops_release',
            new_name='ope_release',
        ),
    ]
