# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0007_auto_20180403_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='dba_release',
            name='sql_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dba_release',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ops_release',
            name='online_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ops_release',
            name='pre_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dba_release',
            name='request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
