# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-11 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0010_dev_release_dev_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='is_have_sql',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='dba_release',
            name='sql_action_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='dev_release',
            name='ops_to_online_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='ops_release',
            name='ops_to_online_status',
            field=models.BooleanField(default=0),
        ),
    ]
