# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-11 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0011_auto_20180411_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dev_release',
            old_name='ops_to_online_status',
            new_name='dev_to_online_status',
        ),
    ]
