# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-11 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0015_activity_release'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activity_release',
        ),
    ]
