# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-11 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0016_delete_activity_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
            ],
        ),
    ]
