# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0016_auto_20180511_0658'),
        ('release', '0017_activity_release'),
    ]

    operations = [
    ]
