# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-25 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0018_merge_20180518_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_release',
            old_name='request_id1',
            new_name='request_id',
        ),
    ]
