# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmdbmanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('uid', models.CharField(max_length=30)),
                ('server_ip', models.CharField(max_length=30)),
                ('server_mem', models.CharField(max_length=30)),
                ('server_cpu', models.CharField(max_length=50)),
                ('server_system', models.CharField(max_length=30)),
                ('server_service', models.CharField(max_length=30)),
                ('operation', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=30)),
            ],
        ),
    ]
