# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('project_description', models.CharField(blank=True, max_length=2048)),
                ('project_label', models.CharField(max_length=500)),
                ('storage_id', models.IntegerField()),
                ('remote_path', models.CharField(blank=True, max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('back_path', models.CharField(max_length=999)),
                ('git_path', models.CharField(max_length=999)),
                ('staging_path', models.CharField(max_length=999)),
                ('sync_script', models.CharField(max_length=999)),
                ('branch_name', models.CharField(max_length=10)),
                ('enable_pre_env', models.CharField(max_length=10)),
                ('staging_path_for_pre', models.CharField(blank=True, max_length=999)),
                ('sync_script_for_pre', models.CharField(blank=True, max_length=999)),
            ],
        ),
    ]
