# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manegement', '0002_remove_project_remote_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remote_path',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
