# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-24 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manegement', '0005_auto_20180515_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pre_remote_path',
            field=models.CharField(blank=True, default=b'none', max_length=999),
        ),
    ]
