# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0003_auto_20180403_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ops_Release',
            new_name='Ope_Release',
        ),
    ]
