# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0009_auto_20180409_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev_release',
            name='dev_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
