# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-06 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='envdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.IntegerField(blank=True, db_index=True)),
                ('envname', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='nginxdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.CharField(blank=True, db_index=True, max_length=30)),
                ('projectname', models.CharField(blank=True, max_length=30)),
                ('filename', models.CharField(blank=True, max_length=30)),
                ('modifytime', models.CharField(blank=True, max_length=30)),
                ('content', models.TextField(blank=True)),
                ('lastcontent', models.TextField(blank=True)),
                ('env', models.IntegerField(blank=True)),
            ],
        ),
    ]
