# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-06 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configures', '0004_auto_20180606_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nginxdb',
            name='projectid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='phpfpmdb',
            name='projectid',
            field=models.IntegerField(db_index=True),
        ),
    ]
