# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manegement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='remote_path',
        ),
    ]
