# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manegement', '0003_project_remote_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cmdb_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
