# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manegement', '0004_project_cmdb_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='sync_script',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='sync_script_for_pre',
        ),
    ]
