# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-23 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_ops_with_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ops_with_project',
        ),
    ]
